# Generated by Django 4.2.11 on 2024-04-23 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_exparation',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 3, 4, 5, 188760)),
        ),
    ]
