# Generated by Django 4.2.11 on 2024-04-23 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_otp_exparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_exparation',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 3, 7, 36, 263150)),
        ),
    ]
