# Generated by Django 4.2.11 on 2024-04-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discusion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
